"""Generates port/linux/src/overlay_font.h, the settings overlay's font
(port/linux/src/overlay.c): printable ASCII of Titillium Web SemiBold
(port/third_party/titillium-web), as a signed distance field atlas, so the
overlay draws it sharp at any size with one small texture.

Each glyph is drawn large, its distance field computed there and scaled
down: a texel holds 128 on the outline, more inside, and falls to 0 at
SPREAD texels outside it.

Needs Pillow, NumPy and SciPy. Enter `python tools/overlay_font.py`; the
result is checked in, so the build does not run this.
"""

from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "port/third_party/titillium-web/TitilliumWeb-SemiBold.ttf"
OUTPUT = ROOT / "port/linux/src/overlay_font.h"

# texels per em in the atlas, the factor it is drawn larger by, and how far
# the field reaches outside the outline, in atlas texels
SIZE = 32
OVERSAMPLE = 8
SPREAD = 4
ATLAS_WIDTH = 512
FIRST, LAST = 32, 126


def glyph_field(font, character):
    """the glyph's distance field at atlas scale, and its offset from the
    pen (left, top) in atlas texels, or None for a blank glyph"""
    box = font.getbbox(character, anchor="ls")
    if box[2] <= box[0] or box[3] <= box[1]:
        return None
    pad = SPREAD * OVERSAMPLE
    # the drawing, aligned so it scales down to whole texels
    left = box[0] - pad
    top = box[1] - pad
    left -= left % OVERSAMPLE
    top -= top % OVERSAMPLE
    width = box[2] + pad - left
    height = box[3] + pad - top
    width += -width % OVERSAMPLE
    height += -height % OVERSAMPLE
    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=255, anchor="ls")
    inside = np.asarray(image) >= 128
    distance = distance_transform_edt(~inside) - distance_transform_edt(inside)
    field = np.clip(0.5 - distance / (2.0 * SPREAD * OVERSAMPLE), 0.0, 1.0)
    # the average of each block of OVERSAMPLE x OVERSAMPLE
    small = field.reshape(height // OVERSAMPLE, OVERSAMPLE, width // OVERSAMPLE, OVERSAMPLE).mean(axis=(1, 3))
    return np.round(small * 255.0).astype(np.uint8), left // OVERSAMPLE, top // OVERSAMPLE


def main():
    font = ImageFont.truetype(str(FONT), SIZE * OVERSAMPLE)
    ascent, descent = font.getmetrics()
    glyphs = []
    shelf_x = shelf_y = shelf_height = 0
    placed = []
    for code in range(FIRST, LAST + 1):
        character = chr(code)
        advance = font.getlength(character) / OVERSAMPLE
        result = glyph_field(font, character)
        if result is None:
            glyphs.append((0, 0, 0, 0, 0, 0, advance))
            continue
        field, left, top = result
        height, width = field.shape
        if shelf_x + width > ATLAS_WIDTH:
            shelf_x = 0
            shelf_y += shelf_height + 1
            shelf_height = 0
        placed.append((field, shelf_x, shelf_y))
        glyphs.append((shelf_x, shelf_y, width, height, left, top, advance))
        shelf_x += width + 1
        shelf_height = max(shelf_height, height)
    atlas_height = shelf_y + shelf_height
    atlas_height += -atlas_height % 4
    atlas = np.zeros((atlas_height, ATLAS_WIDTH), np.uint8)
    for field, x, y in placed:
        atlas[y:y + field.shape[0], x:x + field.shape[1]] = field

    lines = [
        "/*",
        "OVERLAY_FONT.H",
        "",
        "Generated by tools/overlay_font.py: do not edit. Printable ASCII of",
        "Titillium Web SemiBold (port/third_party/titillium-web, SIL Open Font",
        "License 1.1) as a signed distance field for the settings overlay",
        "(overlay.c). A texel is 128 on the outline, and changes by 128 every",
        "OVERLAY_FONT_SPREAD texels.",
        "*/",
        "",
        "#ifndef __HALO_LINUX_OVERLAY_FONT_H",
        "#define __HALO_LINUX_OVERLAY_FONT_H",
        "",
        f"#define OVERLAY_FONT_SIZE {SIZE}",
        f"#define OVERLAY_FONT_SPREAD {SPREAD}",
        f"#define OVERLAY_FONT_ASCENT {ascent / OVERSAMPLE:.3f}f",
        f"#define OVERLAY_FONT_DESCENT {descent / OVERSAMPLE:.3f}f",
        f"#define OVERLAY_FONT_FIRST {FIRST}",
        f"#define OVERLAY_FONT_LAST {LAST}",
        f"#define OVERLAY_FONT_ATLAS_WIDTH {ATLAS_WIDTH}",
        f"#define OVERLAY_FONT_ATLAS_HEIGHT {atlas_height}",
        "",
        "/* in atlas texels; left and top place the box from the pen on the",
        "baseline (top is negative above it) */",
        "struct overlay_glyph",
        "{",
        "\tunsigned short x, y, width, height;",
        "\tshort left, top;",
        "\tfloat advance;",
        "};",
        "",
        "static const struct overlay_glyph overlay_font_glyphs[OVERLAY_FONT_LAST - OVERLAY_FONT_FIRST + 1] =",
        "{",
    ]
    for code, (x, y, width, height, left, top, advance) in zip(range(FIRST, LAST + 1), glyphs):
        name = "space" if code == 32 else "backslash" if code == 92 else chr(code)
        lines.append(f"\t{{ {x}, {y}, {width}, {height}, {left}, {top}, {advance:.3f}f }}, /* {name} */")
    lines += [
        "};",
        "",
        "static const unsigned char overlay_font_atlas[OVERLAY_FONT_ATLAS_WIDTH * OVERLAY_FONT_ATLAS_HEIGHT] =",
        "{",
    ]
    flat = atlas.reshape(-1)
    for start in range(0, flat.size, 32):
        lines.append("\t" + ",".join(str(value) for value in flat[start:start + 32]) + ",")
    lines += ["};", "", "#endif", ""]
    OUTPUT.write_text("\n".join(lines), newline="\n")
    print(f"{OUTPUT.relative_to(ROOT)}: {ATLAS_WIDTH}x{atlas_height} atlas")


if __name__ == "__main__":
    main()
